import AppKit
import Combine
import Foundation

/// AppKit adapter for the pure `ClipboardHistoryStore`. Capture is explicitly
/// opt-in, stays in-process, and never sends clipboard contents off-device.
@MainActor
public final class ClipboardHistoryService: ObservableObject {
    public static let shared = ClipboardHistoryService()

    public static let enabledDefaultsKey = "utilityClipboardHistoryEnabled"
    public static let limitDefaultsKey = "utilityClipboardHistoryLimit"

    @Published public var isEnabled: Bool {
        didSet {
            if persistsPreferences {
                UserDefaults.standard.set(isEnabled, forKey: Self.enabledDefaultsKey)
            }
            if !isEnabled { timer?.invalidate(); timer = nil }
            else { beginObservingIfNeeded() }
        }
    }
    @Published public private(set) var items: [ClipboardHistoryItem] = []

    public var limit: Int {
        didSet {
            limit = max(1, limit)
            if persistsPreferences { UserDefaults.standard.set(limit, forKey: Self.limitDefaultsKey) }
            store.limit = limit
            refreshItems()
        }
    }

    public var itemToRestore: ClipboardContent? { items.first?.content }

    private var store: ClipboardHistoryStore
    private var timer: Timer?
    private var lastChangeCount: Int
    private let persistsPreferences: Bool

    public init(isEnabled: Bool? = nil, limit: Int? = nil, persistsPreferences: Bool = true) {
        self.persistsPreferences = persistsPreferences
        let storedLimit = UserDefaults.standard.object(forKey: Self.limitDefaultsKey) as? Int ?? 20
        self.limit = max(1, limit ?? storedLimit)
        self.isEnabled = isEnabled ?? (UserDefaults.standard.object(forKey: Self.enabledDefaultsKey) as? Bool ?? false)
        store = ClipboardHistoryStore(limit: self.limit)
        lastChangeCount = NSPasteboard.general.changeCount
        if self.isEnabled { beginObservingIfNeeded() }
    }

    public func record(_ content: ClipboardContent, sourceBundleID: String? = nil) {
        guard isEnabled else { return }
        store.record(content, sourceBundleID: sourceBundleID)
        refreshItems()
    }

    public func remove(_ item: ClipboardHistoryItem) {
        store.remove(id: item.id)
        refreshItems()
    }

    public func clearHistory() {
        store.removeAll()
        refreshItems()
    }

    public func stopObserving() {
        timer?.invalidate()
        timer = nil
    }

    public func setPinned(_ isPinned: Bool, for item: ClipboardHistoryItem) {
        store.setPinned(isPinned, id: item.id)
        refreshItems()
    }

    /// Writes a selected history item back to the general pasteboard. The change
    /// counter is immediately re-baselined so Notch never records its own restore.
    public func restore(_ item: ClipboardHistoryItem) {
        let board = NSPasteboard.general
        board.clearContents()
        switch item.content {
        case let .text(text): board.setString(text, forType: .string)
        case let .image(data): board.setData(data, forType: .tiff)
        case let .file(url): board.writeObjects([url as NSURL])
        }
        lastChangeCount = board.changeCount
    }

    private func beginObservingIfNeeded() {
        guard timer == nil else { return }
        lastChangeCount = NSPasteboard.general.changeCount
        let timer = Timer(timeInterval: 0.5, repeats: true) { [weak self] _ in
            Task { @MainActor in self?.captureIfChanged() }
        }
        timer.tolerance = 0.25
        RunLoop.main.add(timer, forMode: .common)
        self.timer = timer
    }

    private func captureIfChanged() {
        let board = NSPasteboard.general
        guard board.changeCount != lastChangeCount else { return }
        lastChangeCount = board.changeCount
        guard let content = read(board) else { return }
        store.record(content)
        refreshItems()
    }

    private func read(_ board: NSPasteboard) -> ClipboardContent? {
        let types = board.types ?? []
        let excluded = ["org.nspasteboard.ConcealedType", "org.nspasteboard.TransientType", "org.nspasteboard.AutoGeneratedType"]
        guard !excluded.contains(where: { types.contains(NSPasteboard.PasteboardType($0)) }) else { return nil }
        if let text = board.string(forType: .string) { return .text(text) }
        if let urls = board.readObjects(forClasses: [NSURL.self]) as? [URL], let url = urls.first { return .file(url) }
        if let image = board.data(forType: .tiff) { return .image(image) }
        return nil
    }

    private func refreshItems() { items = store.items }
}
