import { useState } from 'react'
import './App.css'

const navItems = [['Product', '#product'], ['Agents', '#agents'], ['Privacy', '#privacy'], ['License', '#license']]
const features = [
  { number: '01', title: 'Ask in the moment', text: 'Write a question where your attention already is. NotchFlow streams a focused answer without asking you to context-switch.', icon: 'spark' },
  { number: '02', title: 'Let intent do the sorting', text: 'A thought becomes an answer, note, reminder, or agent task—while the selected destination stays visible and in your control.', icon: 'split' },
  { number: '03', title: 'Keep your Mac in flow', text: 'Files, media, clipboard context, reminders, and useful system signals have one quiet place to land.', icon: 'orbit' },
]
const faqs = [
  ['Does NotchFlow need a hardware notch?', 'No. On Macs without a notch and on external displays, NotchFlow draws a virtual notch and behaves the same way.'],
  ['Do I need an account or an API key?', 'NotchFlow has no product account. Use a provider API key or a supported sign-in flow, or connect a locally installed and signed-in CLI such as Codex or Claude Code.'],
  ['What happens after the seven-day trial?', 'NotchFlow blocks product features until you activate a valid paid license. The license is perpetual and includes future NotchFlow updates.'],
  ['Where does my data go?', 'Your prompts, history, files, notes, and agent records stay on your Mac. Requests go directly to the provider, CLI, or search service you choose; NotchFlow does not relay them through its own backend.'],
]

function Arrow() { return <svg aria-hidden="true" className="arrow" viewBox="0 0 20 20" fill="none"><path d="M3.5 10h12M11 5.5 15.5 10 11 14.5" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" /></svg> }
function Mark() { return <img className="brand-mark" src="/icon.png" alt="" /> }
function FeatureIcon({ type }) {
  const paths = {
    spark: <><path d="m12 2 1.54 5.46L19 9l-5.46 1.54L12 16l-1.54-5.46L5 9l5.46-1.54L12 2Z" /><path d="m5 15 .7 2.3L8 18l-2.3.7L5 21l-.7-2.3L2 18l2.3-.7L5 15Z" /></>,
    split: <><path d="M4 5h6M4 12h5M4 19h7" /><path d="m15 3 4 2.5v5L15 13l-4-2.5v-5L15 3Z" /></>,
    orbit: <><circle cx="12" cy="12" r="3" /><path d="M4.5 6.8C7.6 2.6 15.4 2.9 18.1 7.4c2.5 4.2-.2 9.7-5 10.5-4.7.7-8.6-3.2-7.7-7.7.4-2.1 1.7-4 3.5-5.1" /></>,
  }
  return <svg className="feature-icon" aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.35" strokeLinecap="round" strokeLinejoin="round">{paths[type]}</svg>
}

function Header() {
  const [open, setOpen] = useState(false)
  const close = () => setOpen(false)
  return <header className="site-header"><a className="brand" href="#top" onClick={close} aria-label="NotchFlow home"><Mark /><span>NotchFlow</span></a><nav className="nav-links" aria-label="Primary navigation">{navItems.map(([label, href]) => <a key={href} href={href}>{label}</a>)}</nav><div className="nav-actions"><a className="text-link" href="https://github.com/sidhxntt/notchflow" target="_blank" rel="noreferrer">GitHub</a><a className="button button--small" href="https://github.com/sidhxntt/notchflow/releases/latest" target="_blank" rel="noreferrer">Download <Arrow /></a></div><button className="menu-button" type="button" aria-expanded={open} aria-controls="mobile-menu" onClick={() => setOpen(!open)}><span /><span /><span className="sr-only">{open ? 'Close navigation' : 'Open navigation'}</span></button><div id="mobile-menu" className={`mobile-menu ${open ? 'mobile-menu--open' : ''}`}>{navItems.map(([label, href]) => <a key={href} href={href} onClick={close}>{label}</a>)}<a href="https://github.com/sidhxntt/notchflow/releases/latest" target="_blank" rel="noreferrer" onClick={close}>Download for macOS <Arrow /></a></div></header>
}

function Hero() {
  return <section className="hero" id="top"><div className="orb orb--hero-a" /><div className="orb orb--hero-b" /><div className="orb orb--hero-c" /><div className="hero-copy"><p className="availability"><span /> Direct download · macOS 14+ · Apple silicon</p><h1>Your notch,<br />always ready.</h1><p className="hero-text">Ask, save a note, set a reminder, or hand a task to an AI agent—from the smallest useful place on your Mac.</p><div className="hero-actions"><a className="button" href="https://github.com/sidhxntt/notchflow/releases/latest" target="_blank" rel="noreferrer">Download for macOS <Arrow /></a><a className="button button--outline" href="#product">See the flow <Arrow /></a></div></div><div className="hero-stage" aria-label="NotchFlow app preview"><div className="stage-topline"><span>NotchFlow</span><span>Capture / Ask / Act</span></div><div className="notch-shell"><div className="notch-bar"><span /><span /><span /></div><div className="notch-glow" /><div className="notch-content"><div className="demo-tabs"><span className="demo-tab demo-tab--active">Ask</span><span className="demo-tab">Note</span><span className="demo-tab">Remind</span><span className="demo-tab">Agent</span></div><p className="demo-prompt">What should I focus on next?</p><div className="demo-answer"><span className="answer-dot" /><p>Start with the task that needs a decision. Everything else can wait.</p></div><div className="demo-input"><span>Ask anything</span><b>↵</b></div></div></div><div className="stage-caption"><span>One calm surface for the things that matter now.</span><span>01 / 04</span></div></div></section>
}

function ProductPreview() { return <section className="section product-section" id="product"><div className="section-intro"><p className="eyebrow">Designed for the next useful action</p><h2>Less switching.<br />More flow.</h2><p>NotchFlow understands the shape of a thought and gives it a place to go. The interaction remains small; the possibilities do not.</p></div><div className="product-composition"><figure className="product-frame product-frame--wide"><img src="/product/verb-ask.jpg" alt="NotchFlow answering a question inside the Mac notch" /><figcaption>Ask, without leaving what you are doing.</figcaption></figure><div className="product-rail"><article className="quote-card"><p>“It feels less like opening an app and more like noticing a useful thought.”</p><span>A calmer way to use your Mac</span></article><figure className="product-frame product-frame--small"><img src="/product/verb-note-saved.jpg" alt="NotchFlow confirming a saved note" /><figcaption>A note, saved before it slips away.</figcaption></figure></div></div></section> }
function Features() { return <section className="section feature-section"><div className="section-heading section-heading--center"><p className="eyebrow">A new home for small intentions</p><h2>Capture the thought.<br />Keep the momentum.</h2></div><div className="feature-grid">{features.map((feature) => <article className="feature-card" key={feature.number}><div className="feature-card-top"><span>{feature.number}</span><FeatureIcon type={feature.icon} /></div><h3>{feature.title}</h3><p>{feature.text}</p></article>)}</div></section> }
function AgentSection() { return <section className="agents" id="agents"><div className="agents-orb" /><div className="agents-copy"><p className="eyebrow eyebrow--dark">Your coding agents, within reach</p><h2>Stay with the work<br />without chasing it.</h2><p>NotchFlow watches the local Codex and Claude Code sessions you choose. See what needs a decision, send a follow-up, or jump back to the original session.</p><a className="dark-link" href="#privacy">Built around local control <Arrow /></a></div><div className="agent-preview"><div className="agent-preview-head"><span><i /> Codex · NotchFlow</span><span>Working</span></div><img src="/product/agent-answer.jpg" alt="NotchFlow showing the progress and response from an agent task" /><div className="agent-preview-foot"><span>Approvals only appear when Agentic mode is on.</span><span>Open session <Arrow /></span></div></div></section> }
function TrustSection() { return <section className="section trust-section"><div className="trust-intro" id="privacy"><p className="eyebrow">Private by default</p><h2>Your data stays<br />on your side.</h2><p>NotchFlow has no account and no user-data backend. Your prompts, local history, notes, files, and agent records remain on your Mac. Requests go directly to the provider, CLI, or search service you select.</p><a className="inline-link" href="https://github.com/sidhxntt/notchflow/blob/main/PRIVACY.md" target="_blank" rel="noreferrer">Read the privacy policy <Arrow /></a></div><div className="trust-grid"><article><span className="trust-number">01</span><h3>Local-first</h3><p>Choose your own provider, use a local endpoint, or connect the CLI that is already signed in.</p></article><article><span className="trust-number">02</span><h3>Explicit context</h3><p>Attachments and selected context are visible before you send them.</p></article><article><span className="trust-number">03</span><h3>Real control</h3><p>NotchFlow never auto-approves an agent request. You make every decision.</p></article></div></section> }
function LicenseSection() { return <section className="section license-section" id="license"><div className="license-orb license-orb--one" /><div className="license-orb license-orb--two" /><div className="license-copy"><p className="eyebrow">Simple ownership</p><h2>Try it for seven days.<br />Keep it for good.</h2><p>Every new installation starts with a full seven-day trial. A paid NotchFlow license is perpetual—not a subscription—and includes future updates.</p><a className="button" href="https://github.com/sidhxntt/notchflow/releases/latest" target="_blank" rel="noreferrer">Get NotchFlow <Arrow /></a></div><div className="license-points"><div><strong>7</strong><span>days to explore<br />every feature</span></div><div><strong>∞</strong><span>future updates<br />included</span></div><p>One direct download. No product account.</p></div></section> }
function FAQ() { const [active, setActive] = useState(0); return <section className="section faq-section" id="faq"><div className="faq-heading"><p className="eyebrow">Questions, answered</p><h2>Good to know.</h2><p>Still curious? Open an issue and we will help.</p><a className="inline-link" href="https://github.com/sidhxntt/notchflow/issues" target="_blank" rel="noreferrer">Visit support <Arrow /></a></div><div className="faq-list">{faqs.map(([question, answer], index) => <article className="faq-item" key={question}><button type="button" aria-expanded={active === index} onClick={() => setActive(active === index ? -1 : index)}><span>{question}</span><span className="faq-plus">{active === index ? '−' : '+'}</span></button><div className={`faq-answer ${active === index ? 'faq-answer--open' : ''}`}><p>{answer}</p></div></article>)}</div></section> }
function Footer() { return <footer className="footer"><div className="footer-top"><div><a className="brand" href="#top"><Mark /><span>NotchFlow</span></a><p>Your notch, always ready.</p></div><div className="footer-links"><div><span>Product</span><a href="#product">Overview</a><a href="#agents">Agents</a><a href="#license">License</a></div><div><span>Resources</span><a href="https://github.com/sidhxntt/notchflow" target="_blank" rel="noreferrer">GitHub</a><a href="https://github.com/sidhxntt/notchflow/releases" target="_blank" rel="noreferrer">Releases</a><a href="https://github.com/sidhxntt/notchflow/issues" target="_blank" rel="noreferrer">Support</a></div><div><span>Legal</span><a href="https://github.com/sidhxntt/notchflow/blob/main/PRIVACY.md" target="_blank" rel="noreferrer">Privacy</a><a href="https://github.com/sidhxntt/notchflow/blob/main/LICENSE" target="_blank" rel="noreferrer">License</a></div></div></div><div className="footer-bottom"><span>© 2026 NotchFlow</span><span>Built for macOS</span></div></footer> }

function App() { return <><Header /><main><Hero /><ProductPreview /><Features /><AgentSection /><TrustSection /><LicenseSection /><FAQ /></main><Footer /></> }
export default App
