import Foundation

struct IntentExampleSet {
    let ask: [String]
    let note: [String]
}
/// English-only training data for `IntentEngine`.
enum IntentExamples {
    static let english = IntentExampleSet(ask: englishAsk, note: englishNote)

    private static let englishAsk: [String] = [
        "what is quantum entanglement",
        "why is the sky blue",
        "how do i exit vim",
        "how to convert pdf to word",
        "who invented the telephone",
        "which coffee maker should i buy",
        "what's the speed of light",
        "how far is the moon",
        "what time is it in new york",
        "when is easter this year",
        "is rust faster than go",
        "should i use tabs or spaces",
        "can dogs eat grapes",
        "does coffee dehydrate you",
        "do i need a visa for japan",
        "whats the capital of australia",
        "how tall is mount everest",
        "who wrote the great gatsby",
        "when did ww2 end",
        "how old is the universe",
        "what does serendipity mean",
        "define ephemeral",
        "what's the plural of octopus",
        "is it affect or effect here",
        "what rhymes with orange",
        "what does this acronym mean SLA",
        "apple stock price",
        "is tesla overvalued",
        "what is the fed rate now",
        "how do mortgages work",
        "explain index funds",
        "whats an etf",
        "how much should i save for retirement",
        "can i break a lease early",
        "how to negotiate salary",
        "what to say in an exit interview",
        "how do i answer tell me about yourself",
        "what is okr",
        "how to run a retrospective",
        "how does https work",
        "what is a monad",
        "git undo last commit",
        "how to center a div",
        "why is my build so slow",
        "what's the difference between docker and a vm",
        "what is rag in llms",
        "how do i write better prompts",
        "claude vs chatgpt for coding",
        "whats trending in ai right now",
        "how to take a screenshot on mac",
        "how do i turn off notifications on iphone",
        "why is my wifi so slow",
        "my keyboard is typing double letters how to fix",
        "should i upgrade to the new macbook",
        "m4 vs m3 performance difference",
        "how much ram do i need for video editing",
        "best budget monitor for coding",
        "does airplane mode save battery",
        "how do solar panels work",
        "why do cats purr",
        "why do we dream",
        "how do planes fly",
        "is intermittent fasting safe",
        "how much water should i drink a day",
        "what's a normal resting heart rate",
        "how to fall asleep faster",
        "how to deal with jet lag",
        "my back hurts from sitting what should i do",
        "is it ok to run every day",
        "how many calories in an avocado",
        "how accurate are calorie counters",
        "how long to boil eggs",
        "can you freeze cheese",
        "how long does cooked rice last in the fridge",
        "what wine goes with salmon",
        "how to make cold brew at home",
        "difference between espresso and ristretto",
        "how to keep bananas fresh longer",
        "what should i cook tonight",
        "how do i remove a wine stain",
        "why does my plant have yellow leaves",
        "how often should i water a monstera",
        "whats a good gift for a 5 year old",
        "what milk should i buy",
        "cheapest time to fly to europe",
        "is september a good time to visit japan",
        "explain the offside rule",
        "how does scoring work in tennis",
        "rules of texas holdem",
        "how to solve a rubik's cube",
        "chess opening for beginners",
        "how to tie a tie",
        "how to iron a shirt without an iron",
        "whats the dress code for a summer wedding",
        "best way to learn piano",
        "how do you say cheers in german",
        // imperatives: work handed to the AI
        "summarize this article",
        "translate hello to japanese",
        "translate this to french see you tomorrow",
        "write a haiku about rain",
        "write a polite decline email",
        "write an email to my boss about the delay",
        "draft a cover letter for a pm role",
        "write a toast for my brother's wedding",
        "write a standup update from these notes",
        "write interview questions for a backend engineer",
        "explain transformers like i'm five",
        "explain this error message",
        "fix this regex",
        "debug this swift code",
        "review my resume",
        "proofread this email",
        "compare react and svelte",
        "convert 80 kg to lbs",
        "convert 100 usd to eur",
        "calculate 15% tip on 86",
        "give me a 7 day workout plan",
        "give me dinner ideas with chicken",
        "recommend some sci-fi books",
        "suggest a name for my cat",
        "make this sentence more formal",
        "rewrite this in simple english",
        "shorten this to one paragraph",
        "turn this into bullet points",
        "summarize this meeting transcript",
        "brainstorm taglines for a coffee shop",
        "plan a 3 day itinerary for tokyo",
        "make a packing list for a beach trip",
        "quiz me on european capitals",
        "teach me basic spanish phrases",
        "tell me a joke",
        "tell me a bedtime story about a dragon",
        "continue this story",
        "ideas for a team offsite",
        "icebreaker questions for a meeting",
        "air fryer salmon recipe",
        "stretch routine for desk workers",
        "excel formula to count unique values",
        "show me how to make a pivot table",
        "keyboard shortcut for emoji on mac",
        "what should i name my wifi",
        // planning / generation asks (mirror of listy notes)
        "plan a weekend trip to kyoto",
        "plan a birthday party for a 6 year old",
        "build me a study plan for ielts",
        "make me a workout for leg day",
        "give me ideas for date night",
        "what should i read after atomic habits",
        "whats worth watching on netflix right now",
        "what's a good podcast about startups",
        "remind me how reduce works in python",
        // number-flavored asks (digits shouldn't drag a question into note)
        "how many days until christmas",
        "what is 18% of 230",
        "square root of 7056",
        "how many ounces in a liter",
        "whats 230 euros in dollars",
        "how long is a marathon",
        // title / media asks (book and show names shouldn't read as a queue jot)
        "who directed inception",
        "who sings bohemian rhapsody",
        "who painted the starry night",
        "is the three body problem worth reading",
        "what is dune about",
        "summary of atomic habits",
        "is severance any good",
        "books like project hail mary",
        // noun-phrase information asks (no verb, still a lookup)
        "best stretches for lower back",
        "dinner ideas without meat",
        "gift ideas for mom",
        "weekend trip ideas near seattle",
        "side effects of melatonin",
        "difference between 401k and ira",
        "pros and cons of electric cars",
        "meaning of deja vu",
        "synonyms for happy",
        "capital of switzerland",
        "population of japan",
        "calories in a banana",
        // pure arithmetic (digit-heavy but still a question)
        "what's 48 plus 67",
        "1024 divided by 3",
        "98 times 76",
        "what is 2 to the 10th",
        "sqrt of 144",
        "cube root of 729",
        "factorial of 10",
        "what's 20% off 149",
        "average of 12 18 25",
        "30 dollars a day for a year is how much",
        // greetings / social / meta-dialogue aimed at the assistant, not a jot
        "hello",
        "hello there",
        "hi",
        "hi there",
        "hey",
        "hey there",
        "good morning",
        "good evening",
        "how are you",
        "how's it going",
        "thanks",
        "thank you",
        "thanks a lot",
        "who are you",
        "what are you",
        "what can you do",
        "what's your name",
        "tell me about yourself",
        "let's chat",
        "talk to me",
        "keep going",
        "continue",
        "try again",
        "another one",
        "more detail please",
        "make it simpler",
        "i didn't get that explain again",
        // App-setting commands are assistant tasks: route them to Ask so the
        // confirmed settings tool sees them, never into the note capture path.
        "hide the app icon from the dock",
        "don't show the menu bar icon",
        "don't launch this app at login",
        "start this app automatically when i log in",
        "set hover sensitivity to low",
        "save my notes to a markdown folder",
        "change the summon shortcut to command shift k",
        "show me all current app settings",
        "what keyboard shortcuts does this app have",
        "which hotkeys does notch support",
        "what is the shortcut to summon the app",
        // question-marked variants (the mark itself is a cue worth teaching;
        // the Chinese set carries a couple of these too)
        "hello?",
        "are you there?",
        "can dogs eat grapes?",
        "what time is it in tokyo?",
        "is this correct?",
        "how does this work?",
        "any ideas?",
    ]

    // MARK: - English · note

    private static let englishNote: [String] = [
        // todos
        "buy milk",
        "milk eggs bread detergent",
        "pick up dry cleaning",
        "call mom",
        "call the dentist tomorrow",
        "renew passport",
        "pay rent",
        "pay electricity bill",
        "email the landlord about the leak",
        "reply to hr about offer by friday",
        "detergent almost out",
        "cat food 3 days left",
        "top up laundry card",
        "bring badge",
        "wear formal tomorrow client visit",
        "ikea this weekend look at sofas",
        "black friday list vacuum air fryer",
        "groceries soy sauce vinegar garlic ginger",
        "replace badge at reception",
        "parents visiting next week clean guest room",
        "sleep in sunday",
        "rsvp by friday",
        // time-stamped
        "dentist tuesday 3pm",
        "rent due friday",
        "flight ua882 june 18 9:40am",
        "train to boston 7:05 track 9",
        "lunch with li wed 12:30",
        "dinner 7pm hotpot with kai",
        "parent teacher meeting thu 7pm",
        "piano moved to saturday 10am",
        "haircut sat 11am with tony",
        "interview candidate wed 2pm ios role",
        "booked room 1401 for 4pm",
        "monday standup moved to 9:30",
        "team dinner tonight eat light",
        "reunion aug 2 old campus",
        "lab results ready thursday",
        "second shot june 25",
        "braces checkup every 6 weeks",
        "car ready thursday says mechanic",
        "up at 6:30 to catch the train",
        "set alarm for 5:50",
        "shuttle leaves 6:10 north gate",
        "pickup point closes at 8pm",
        "cafeteria has grilled fish wednesday",
        "that shop closed mondays",
        "expense report due end of month",
        "deadline paper submission july 15",
        "server renews june 30",
        "car insurance renews july 8",
        "license renewal before december",
        "passport expires march 2027",
        "gym membership expires in march",
        "contacts due end of april",
        "mortgage autopay on the 19th",
        "preschool lunch fee 300",
        // info jots
        "wifi pw sunflower99",
        "guest wifi cafe_blue pass latte2026",
        "parked on b2-077",
        "parking spot 144 level 3",
        "locker code 0427",
        "gym locker 217",
        "gate code #2046",
        "hotel confirmation 8829137",
        "airbnb checkin 3pm code 4416",
        "airbnb address 12 rue cler",
        "key at front desk under my name",
        "itinerary osaka 3d kyoto 2d",
        "visa docs employment letter bank statement photos",
        "new coworker is priya on design",
        "landlord number 555 0132",
        "building mgmt 555 8821",
        "invoice number 2026-0613",
        "tax id 84-2210334",
        "salary hits the 6679 card",
        "hoa fee 280 paid",
        "insurance policy picc2026088123",
        "changed password to Glass#2026",
        "router admin 192.168.31.1",
        "test account demo01 pass 123456",
        "macbook serial c02zk1anlvdq",
        "ev charger slot 3 is broken",
        "use 95 octane",
        "tire pressure 2.3 front 2.5 rear",
        "next service at 62000 km",
        "gas meter 3327",
        "package shipped sf1352847569988",
        "return label 773310928",
        "renew domain notchglass.app",
        "metro card under $10",
        "glasses left 4.50 right 4.75",
        "shoe size 37 for sis",
        "leftovers in fridge for lunch",
        "water succulents weekly",
        "vitamin d daily after breakfast",
        "antibiotics until friday",
        "updated 401k contribution to 8%",
        "onboarding docs id diploma health report",
        // reminder phrasing
        "remember to water the plants",
        "remember sunscreen tomorrow",
        "don't forget the charger",
        "dont forget lunch with sam",
        "remind me to send the invoice monday",
        "todo update resume email recruiter",
        "todo write weekly report",
        // ideas
        "idea pomodoro timer in the notch",
        "idea for blog ai and attention",
        "app idea split bills with roommates",
        "gift idea for dad fishing rod",
        "mom's birthday may 12",
        "anniversary sept 3",
        "idea recent as a timeline",
        "research raycast ai entry ux",
        "competitors alfred spotlight raycast",
        "bug hint flickers while typing",
        "fix settings scrollbar",
        "shipped v0.4.2",
        "wedding gift 800 for zhou",
        // records / logs
        "weight 71.5 kg",
        "ran 5k today 27:40",
        "bench 3x8 at 60kg",
        "blood pressure 122/79",
        "day 7 no sugar",
        "no bubble tea day 3",
        "lights out by 11",
        "talked to landlord answer by end of month",
        "boss said q3 budget cut 10%",
        "sent the mockups to jake",
        "meeting notes v1 design due tuesday",
        "weekly report shipped auto routing",
        "q3 okr retention +5%",
        "late night taxi is reimbursable",
        "trainer says start with back",
        "book note focus is scarce",
        "quote slow is smooth smooth is fast",
        "movies to watch dune 2 oppenheimer",
        "show rec severance s2",
        "add to playlist lemon kenshi yonezu",
        "reading list thinking fast and slow",
        "restaurant shortlist tsuta konjiki hototogisu",
        "coffee beans yirgacheffe medium roast good",
        "sofa kivik 4999",
        // remind-me phrasing (the note side of "remind me")
        "remind me to call the bank",
        "remind me about the dentist thursday",
        "remind me to take out the trash tonight",
        "remind me to renew the parking permit",
        // media / reading queues
        "books to read atomic habits deep work",
        "watchlist the bear season 3",
        "to watch shogun",
        "to read the three body problem",
        "podcast queue acquired huberman",
        // idea jots
        "idea dark mode for the widget",
        "idea weekly email digest",
        "feature idea quick capture hotkey",
        "startup idea ai meal planner",
        // status logs / done items
        "sent the invoice to acme",
        "sent the deck to legal",
        "pushed the fix to staging",
        "told the landlord about the leak",
        "finished chapter 4",
        "ordered the standing desk",
        "booked flights for august",
        "paid the water bill",
        "submitted the expense report",
        "emailed the professor about office hours",
        // people / facts someone told me
        "new pm is marcus from stripe",
        "sarah moved to the platform team",
        "doctor said cut back on caffeine",
        "mechanic recommends new brake pads soon",
        "dentist rec dr lee on 5th ave",
        // short plans
        "gym after work",
        "leg day tomorrow",
        "no meetings friday",
        "wfh wednesday",
        "early standup tomorrow",
        "date night saturday",
        "movie night sunday with the kids",
        // errands / trip prep lists
        "errands bank post office pharmacy",
        "weekend plans hike farmers market",
        "trip prep buy adapter download maps",
        // deictic captures (referent lives on the clipboard, not in the line)
        "save this link",
        "add this to my reading list",
        "bookmark this",
        "note this url",
        "save this snippet",
        "keep this",
        "file this away",
        "save this for later",
        "jot this down",
        "add this to my notes",
        "save this page",
        "note this down",
    ]
}
