import Foundation

/// One language's labeled examples for training the intent head: lines that read
/// as a question/task for the AI (`ask`) vs. lines that read as a personal jot to
/// file away (`note`).
struct IntentExampleSet {
    let ask: [String]
    let note: [String]
}

/// The training corpus for `IntentEngine` — curated, hand-labeled examples of what
/// people actually type into a launcher-style input, in the two languages the app
/// primarily serves. These are NOT matched against the user's text (this is not a
/// lexicon); they are embedded once with `NLContextualEmbedding` and used to fit a
/// tiny logistic head over the embedding space. Quality and *diversity* of these
/// lines is what the classifier's judgment is made of, so the sets deliberately
/// include the hard boundary pairs a rules engine can't tell apart:
///
///   · "帮我写邮件给老板" (a task for the AI → ask)  vs "发邮件给老板" (a todo → note)
///   · "买什么牛奶好" (ask)                          vs "买牛奶" (note)
///   · "明天会下雨吗" (ask)                          vs "明天交房租" (note)
///   · questions with no question mark, jots that contain "recommend"/"提醒", etc.
///
/// Mixed-language lines ("review 一下我的简历") live in the Chinese set because any
/// Han character routes the text to the CJK embedding model (see `IntentEngine`).
enum IntentExamples {
    static let chinese = IntentExampleSet(ask: chineseAsk, note: chineseNote)
    static let english = IntentExampleSet(ask: englishAsk, note: englishNote)

    // MARK: - Chinese · ask

    private static let chineseAsk: [String] = [
        // 显式疑问(有/无问号都得认识,这里一律不带问号,问号本身另有样本)
        "什么是量子纠缠",
        "为什么天空是蓝色的",
        "怎么把PDF转成Word",
        "如何快速入睡",
        "谁发明了电话",
        "哪个牌子的咖啡机好用",
        "光速是多少",
        "地球到月球有多远",
        "明朝一共多少年",
        "美元兑人民币汇率是多少",
        "120美元等于多少人民币",
        "37度算发烧吗",
        "孩子发烧38度怎么办",
        "高铁能带充电宝吗?",
        "深圳明天会下雨吗",
        "明天适合洗车吗",
        "狗能吃葡萄吗",
        "隔夜菜能吃吗?",
        "智齿一定要拔吗",
        "房贷提前还划算吗",
        "五一高速免费吗",
        "BMI 24算胖吗",
        "黑神话悟空好玩吗",
        "苹果股价多少",
        "特斯拉市值是多少",
        "黄金现在多少钱一克",
        "北京到上海高铁要几个小时",
        "纽约现在几点",
        "今年春节是几月几号",
        "世界杯哪年在美国举办",
        "红楼梦的作者是谁",
        "圆周率后十位是多少",
        "莎士比亚有哪些代表作",
        "小米15什么时候发布",
        "下一代iPhone有什么新功能",
        "M4芯片比M3强多少",
        "人为什么会做梦",
        "猫为什么怕黄瓜",
        "飞机为什么能飞起来",
        "茅台为什么这么贵",
        "维生素C吃多了会怎样",
        "一天喝多少水合适",
        "咖啡喝多了有什么坏处",
        "跑步前要不要拉伸",
        "三个月能减十斤吗",
        "什么时候买机票最便宜",
        "去日本旅游要办什么签证",
        "体脂率怎么算",
        "失眠怎么办",
        "电动车冬天掉电快怎么办",
        "怎么去除衣服上的油渍",
        "冰箱结冰怎么处理",
        "键盘进水了怎么办",
        "Mac怎么截图",
        "微信怎么设置免打扰",
        "怎么注销微博账号",
        "word目录怎么自动生成",
        "Excel怎么做透视表",
        "PPT怎么做才好看",
        "怎么用Keynote做动画",
        "如何提高英语口语",
        "怎么快速学会游泳",
        "滑雪初学者买什么装备",
        "笔记本电脑怎么选",
        "5000预算买什么手机好",
        "买什么牛奶好",
        "学Python还是学Java",
        "30岁转行学编程来得及吗",
        "象棋开局怎么走",
        "德州扑克规则是什么",
        "怎么折千纸鹤",
        "魔方六面还原口诀",
        "怎么哄三岁小孩睡觉",
        "怎么和青春期孩子沟通",
        "怎么礼貌地拒绝加班",
        "面试自我介绍怎么说",
        "离职原因怎么回答比较好",
        "你觉得我该不该跳槽",
        "是不是该换电脑了",
        "这两个方案哪个更好",
        "ChatGPT和Claude哪个好用",
        "大模型的token是什么",
        "什么是RAG",
        "prompt怎么写效果好",
        "怎么看待AI取代程序员",
        "swift的actor是什么",
        "swift里@MainActor是干嘛的",
        "python怎么读取文件",
        "正则怎么匹配中文",
        "git怎么撤销上一次提交",
        "这段代码为什么报错",
        "docker和虚拟机有什么区别",
        "红烧肉怎么做",
        "可乐鸡翅的做法",
        "告诉我怎么做凉拌黄瓜",
        "有什么适合新手的吉他",
        "有没有好用的记账App",
        "怎么辨别羽绒服真假",
        "这个英文单词什么意思 serendipity",
        "serendipity是什么意思",
        "给我解释下这个梗 绝绝子",
        "什么是City Walk",
        "这句话语法对吗 He don't like it",
        "这段话是什么语言",
        "这是什么歌 歌词是岁月是一场有去无回的旅行",
        // 祈使任务:交给 AI 干活
        "帮我写一封请假邮件",
        "帮我写邮件给老板",
        "帮我把这段话翻译成英文",
        "帮我列一个一周健身计划",
        "帮我想几个公众号名字",
        "帮我润色一下这段自我介绍",
        "帮我算一下房贷月供 200万 30年",
        "帮我起几个英文名 男生",
        "帮我分析一下这个offer值不值得去",
        "帮我看看这段SQL哪里慢",
        "帮我写个朋友圈文案 关于跑步",
        "帮我编一个睡前故事",
        "帮我设计一个面试题 考察并发",
        "帮我查一下北京限号",
        "帮我把简历翻译成英文",
        "帮我想一个团建活动方案",
        "翻译成日语 谢谢款待",
        "翻译 The quick brown fox jumps over the lazy dog",
        "把这句话改得正式一点",
        "把这段话缩写到50字",
        "扩写成300字",
        "用一句话解释区块链",
        "用大白话解释什么是基金定投",
        "给五岁小孩解释什么是黑洞",
        "解释一下什么是通货膨胀",
        "解释一下这段报错信息",
        "总结一下这篇文章的要点",
        "给我推荐几本科幻小说",
        "推荐几部高分悬疑电影",
        "对比一下iPhone和华为的拍照",
        "比较React和Vue的优缺点",
        "写一首关于春天的诗",
        "写个周报模板",
        "写一段产品发布会开场白",
        "起草一份租房合同要点",
        "给我讲讲三体的剧情",
        "介绍一下故宫的历史",
        "说说乔布斯的生平",
        "给我一个番茄炒蛋的菜谱",
        "review一下我的简历",
        "优化一下这段文案",
        "检查一下这段话有没有错别字",
        "续写这个故事",
        "想个生日祝福语 给闺蜜",
        "出几道小学三年级数学题",
        "查一下广州天气",
        "200除以7等于多少",
        "80公斤是多少斤",
        "个税专项扣除怎么申报",
        "婚礼致辞怎么写",
        "公司年会节目有什么创意",
        "邮件开头怎么写显得专业",
        "怎么做才能让头发长得快",
        "这个函数有什么问题",
        "面试官问期望薪资怎么回",
        // 数字 / 换算 / 时间类问句(数字本身不该把句子拽成 note)
        "365乘以24等于多少",
        "三分之二加四分之一等于多少",
        "1英里是多少公里",
        "一斤等于多少克",
        "华氏100度是多少摄氏度",
        "帮我换算 5000日元是多少人民币",
        "从上海到杭州开车要多久",
        "现在到春节还有多少天",
        "马拉松全程是多少公里",
        "珠峰有多高",
        "今天农历几号",
        "下个法定节假日是哪天",
        "存款利率现在是多少",
        "公积金贷款利率多少",
        "苹果15和14差价多少",
        "高铁和飞机哪个划算 北京到广州",
        "12306怎么改签",
        "魔方公式有哪些",
        "口算 48加67",
        // 翻译类(混排英文不该被当成 note)
        "翻译 stay hungry stay foolish",
        "翻译 hello world",
        "翻译成中文 to be or not to be",
        "这句英文怎么读 entrepreneur",
        "long time no see 是什么意思",
        // "推荐/提醒" 的 ask 一侧镜像
        "推荐个靠谱的牙医",
        "怎么设置每天提醒我喝水",
        "有什么好看的剧 最近",
        // 纯算术(数字多也仍然是问)
        "2的10次方是多少",
        "1024除以3等于几",
        "98乘以76",
        "567加891等于多少",
        "根号2等于多少",
        "7056的平方根是多少",
        "15的18%是多少",
        "100减35再乘2",
        "42.195公里是多少英里",
        "存10万 年化3.5 一年利息多少",
        // 应用设置指令（必须走 Ask，交给设置工具二次确认；不能被当作随手记）
        "我要把应用语言设置成简体中文",
        "把应用语言换成英文",
        "把程序坞里的应用图标隐藏掉",
        "不要显示菜单栏图标",
        "我不要开机时启动",
        "以后登录时自动启动这个应用",
        "把悬停灵敏度调低一点",
        "关闭全屏时自动隐藏",
        "笔记改成保存到Markdown文件夹",
        "把唤起快捷键改成command shift k",
        "现在应用都有哪些设置",
        "这个应用有哪些快捷键",
        "Notch支持哪些快捷键",
        "唤起应用的快捷键是什么",
        // 寒暄 / 社交 / 元对话(对着 AI 输入框说的话,收件人是助手,不是记给自己的)
        "你好",
        "你好呀",
        "您好",
        "在吗",
        "在不在",
        "早上好",
        "晚上好",
        "下午好",
        "谢谢",
        "谢谢你",
        "辛苦了",
        "你是谁",
        "你叫什么名字",
        "你能做什么",
        "你会什么",
        "介绍一下你自己",
        "我们聊聊天吧",
        "陪我聊聊天",
        "讲个笑话",
        "夸夸我",
        "继续",
        "接着说",
        "换一个",
        "再来一个",
        "详细一点",
        "说得再简单点",
        "没听懂 再解释一遍",
    ]

    // MARK: - Chinese · note

    private static let chineseNote: [String] = [
        // 待办
        "买牛奶",
        "买牛奶 鸡蛋 面包",
        "下班取快递",
        "取快递 丰巢 取件码331808",
        "交电费",
        "明天交房租",
        "给妈妈打电话",
        "预约牙医",
        "周四下午预约牙医",
        "发邮件给老板",
        "给HR回复offer 周五前",
        "洗衣液快没了",
        "猫粮还剩三天",
        "水电卡余额不足 去充值",
        "地铁卡余额不到10块",
        "带工牌",
        "明天穿正装 有客户来",
        "周末去宜家看沙发",
        "双十一买 吸尘器 空气炸锅",
        "购物清单 酱油 醋 蒜 生姜",
        "买 airpods",
        "去银行换新卡",
        "周日补觉",
        "收拾客房 爸妈下周来",
        "给岳父带两条烟",
        // 时间 + 事件
        "明天下午3点和David开会",
        "周五前交报告",
        "下周二上午体检",
        "6月18号机票 北京飞上海 MU5137",
        "高铁G102 周五 9:15 检票口B6",
        "酒店订好了 希尔顿 1208房",
        "孩子家长会 周四晚7点",
        "钢琴课改到周六上午十点",
        "晚上7点 火锅 海底捞 朝阳店",
        "午饭和阿凯 老地方",
        "跟李总约了下周三午饭",
        "面试候选人 周三下午2点 iOS岗",
        "会议室订了 1401 下午4点",
        "周一晨会改到9点半",
        "理发预约 周六11点 Tony",
        "同学聚会 8月2号 老校区",
        "婚礼份子钱 800 小舟",
        "体检报告周四可取",
        "疫苗第二针 6月25号",
        "牙套复诊 每6周一次",
        "修车 师傅说周四能好",
        "明早6:30起来赶高铁",
        "闹钟定5:50",
        "周五例会轮到我主持",
        "下周分享主题 端侧模型",
        "明天 deadline 提交paper",
        "投稿截止 7月15 AAAI",
        "报销截止 月底前",
        "班级群里接龙 周五截止",
        "幼儿园交餐费 300",
        // 备忘信息
        "wifi密码 himalaya2024",
        "公司wifi NotchGuest 密码 glass2026",
        "车停在B2-077",
        "车位 负二层 C区 33号",
        "行李寄存柜 0427",
        "快递柜密码 8-3-2021",
        "小区门禁码 #2046",
        "新同事叫陈晓 产品组",
        "房东电话 13802551122",
        "物业电话 0571-88215566",
        "楼下维修师傅 周师傅 微信同号",
        "发票抬头 杭州山月科技有限公司",
        "税号 91330106MA2GL2T7XQ",
        "银行卡尾号 6679 是工资卡",
        "房贷扣款日 每月19号",
        "物业费 1280 已交",
        "健身房年卡 3月到期",
        "隐形眼镜 4月底换新",
        "车险 7月8号到期",
        "驾照换证 今年12月前",
        "护照2027年3月过期",
        "签证材料 在职证明 流水 照片",
        "行程 大阪3天 京都2天",
        "民宿地址 中京区柳马场通三条",
        "房间钥匙在前台 报姓名即可",
        "保险单号 PICC2026088123",
        "公积金密码改了 旧手机号作废",
        "户口本在妈那里",
        "合同放在第二个抽屉",
        "印章在行政那里 用完登记",
        "密码改成了 Glass#2026",
        "路由器后台 192.168.31.1 admin",
        "测试账号 demo01 密码123456",
        "GitHub token 在1Password里",
        "笔记本序列号 C02ZK1ANLVDQ",
        "充电桩第三个槽是坏的",
        "公司门禁卡补办 找前台",
        "眼镜度数 左450 右475",
        "鞋码 嫂子是37",
        "胎压 前2.3 后2.5",
        "下次保养 62000公里",
        "加95号油",
        "燃气表读数 3327",
        "电表余额 47度",
        "快递已发 顺丰SF1352847569988",
        "退货单号 773310928",
        "服务器到期 6月30",
        "域名续费 notchglass.app",
        "公司班车 晚6:10 北门",
        "楼下快递点晚8点关门",
        "这家店周一闭店",
        "食堂周三有烤鱼",
        "冰箱里有剩饭 明天中午吃",
        "阳台的多肉一周浇一次",
        "维生素D 每天一粒 早饭后",
        "抗生素吃到周五",
        // 提醒短语
        "记得带伞",
        "记得给花浇水",
        "别忘了给猫铲屎",
        "别忘了带充电器",
        "提醒我周一发工资条",
        "提醒我下午两点开会",
        "待办 改简历 发邮件 订酒店",
        "todo 写周报",
        // 想法 / 灵感
        "idea notch里加个番茄钟",
        "想法 周报自动生成工具",
        "文章选题 AI和注意力经济",
        "公众号选题 早起的一百天",
        "灵感 把Recent做成时间轴",
        "调研 Raycast的AI入口交互",
        "竞品 Alfred Spotlight Raycast",
        "bug 中文输入法下hint闪烁",
        "待修 设置页滚动条",
        "版本号 v0.4.2 已发布",
        "送爸爸的生日礼物 鱼竿",
        "妈妈生日 5月12号 农历",
        "老婆纪念日 9月3号",
        // 记录 / 流水
        "今天跑了5公里 28分钟",
        "体重71.5",
        "今天体重70.8 降了",
        "俯卧撑 3组x20",
        "血压 128/82",
        "戒糖第7天",
        "今天没喝奶茶 第3天",
        "早睡打卡 11点前",
        "和房东谈了房租 月底答复",
        "老板说Q3预算砍10%",
        "设计稿链接发给小王了",
        "会议结论 下周二出第一版设计稿",
        "周报要点 上线了自动路由",
        "下季度OKR 留存提升5%",
        "加班打车可以报销",
        "客户王总 偏好微信沟通 别打电话",
        "供应商报价 单价4.2 一万件起订",
        "健身教练推荐 先练背",
        "读书笔记 专注是稀缺资源",
        "金句 慢就是快",
        "电影想看 沙丘2 还有奥本海默",
        "剧推荐 漫长的季节",
        "歌单加 Lemon 米津玄师",
        "书单 置身事内 纳瓦尔宝典",
        "餐厅备选 柴门头啖汤 大龙燚",
        "咖啡豆 耶加雪菲 中度烘焙 好喝",
        "入职材料 身份证 学历证 体检报告",
        "论文改第三章 导师说案例不够",
        "中午别吃太饱 晚上聚餐",
        // "X推荐 Y" / 清单类(别人给的推荐是记下来的事实,不是提问)
        "餐厅推荐 老王家面馆 同事说好吃",
        "牙医推荐 李医生 朝阳门诊",
        "理财师推荐 先买货基",
        "想看的剧 风骚律师 真探",
        "播客清单 得意忘形 疯投圈",
        "语录 种一棵树最好的时间是十年前",
        "句子 凡是过往皆为序章",
        // 状态 / 流水记录
        "今天加班到十点",
        "项目延期到下月初",
        "老师说孩子最近上课走神",
        "买了新键盘 红轴 不错",
        "美元定存到期 6月20",
        "下周出差 周二到周四 上海",
        "团建定在周五 桌游",
        "Q2绩效面谈 下周一",
        "新表已经寄回总部了",
        // 指示性收藏（被指代的内容在剪贴板里，不在句子里）
        "保存这个链接",
        "把这个加到阅读清单",
        "收藏这个",
        "记下这个",
        "保存这个网址",
        "把这段话记下来",
        "存一下这个",
        "保存这个代码片段",
    ]

    // MARK: - English · ask

    private static let englishAsk: [String] = [
        "what is quantum entanglement",
        "why is the sky blue",
        "how do i exit vim",
        "how to convert pdf to word",
        "who invented the telephone",
        "which coffee maker should i buy",
        "what's the speed of light",
        "how far is the moon",
        "what time is it in new york",
        "when is easter this year",
        "is rust faster than go",
        "should i use tabs or spaces",
        "can dogs eat grapes",
        "does coffee dehydrate you",
        "do i need a visa for japan",
        "whats the capital of australia",
        "how tall is mount everest",
        "who wrote the great gatsby",
        "when did ww2 end",
        "how old is the universe",
        "what does serendipity mean",
        "define ephemeral",
        "what's the plural of octopus",
        "is it affect or effect here",
        "what rhymes with orange",
        "what does this acronym mean SLA",
        "apple stock price",
        "is tesla overvalued",
        "what is the fed rate now",
        "how do mortgages work",
        "explain index funds",
        "whats an etf",
        "how much should i save for retirement",
        "can i break a lease early",
        "how to negotiate salary",
        "what to say in an exit interview",
        "how do i answer tell me about yourself",
        "what is okr",
        "how to run a retrospective",
        "how does https work",
        "what is a monad",
        "git undo last commit",
        "how to center a div",
        "why is my build so slow",
        "what's the difference between docker and a vm",
        "what is rag in llms",
        "how do i write better prompts",
        "claude vs chatgpt for coding",
        "whats trending in ai right now",
        "how to take a screenshot on mac",
        "how do i turn off notifications on iphone",
        "why is my wifi so slow",
        "my keyboard is typing double letters how to fix",
        "should i upgrade to the new macbook",
        "m4 vs m3 performance difference",
        "how much ram do i need for video editing",
        "best budget monitor for coding",
        "does airplane mode save battery",
        "how do solar panels work",
        "why do cats purr",
        "why do we dream",
        "how do planes fly",
        "is intermittent fasting safe",
        "how much water should i drink a day",
        "what's a normal resting heart rate",
        "how to fall asleep faster",
        "how to deal with jet lag",
        "my back hurts from sitting what should i do",
        "is it ok to run every day",
        "how many calories in an avocado",
        "how accurate are calorie counters",
        "how long to boil eggs",
        "can you freeze cheese",
        "how long does cooked rice last in the fridge",
        "what wine goes with salmon",
        "how to make cold brew at home",
        "difference between espresso and ristretto",
        "how to keep bananas fresh longer",
        "what should i cook tonight",
        "how do i remove a wine stain",
        "why does my plant have yellow leaves",
        "how often should i water a monstera",
        "whats a good gift for a 5 year old",
        "what milk should i buy",
        "cheapest time to fly to europe",
        "is september a good time to visit japan",
        "explain the offside rule",
        "how does scoring work in tennis",
        "rules of texas holdem",
        "how to solve a rubik's cube",
        "chess opening for beginners",
        "how to tie a tie",
        "how to iron a shirt without an iron",
        "whats the dress code for a summer wedding",
        "best way to learn piano",
        "how do you say cheers in german",
        // imperatives: work handed to the AI
        "summarize this article",
        "translate hello to japanese",
        "translate this to french see you tomorrow",
        "write a haiku about rain",
        "write a polite decline email",
        "write an email to my boss about the delay",
        "draft a cover letter for a pm role",
        "write a toast for my brother's wedding",
        "write a standup update from these notes",
        "write interview questions for a backend engineer",
        "explain transformers like i'm five",
        "explain this error message",
        "fix this regex",
        "debug this swift code",
        "review my resume",
        "proofread this email",
        "compare react and svelte",
        "convert 80 kg to lbs",
        "convert 100 usd to eur",
        "calculate 15% tip on 86",
        "give me a 7 day workout plan",
        "give me dinner ideas with chicken",
        "recommend some sci-fi books",
        "suggest a name for my cat",
        "make this sentence more formal",
        "rewrite this in simple english",
        "shorten this to one paragraph",
        "turn this into bullet points",
        "summarize this meeting transcript",
        "brainstorm taglines for a coffee shop",
        "plan a 3 day itinerary for tokyo",
        "make a packing list for a beach trip",
        "quiz me on european capitals",
        "teach me basic spanish phrases",
        "tell me a joke",
        "tell me a bedtime story about a dragon",
        "continue this story",
        "ideas for a team offsite",
        "icebreaker questions for a meeting",
        "air fryer salmon recipe",
        "stretch routine for desk workers",
        "excel formula to count unique values",
        "show me how to make a pivot table",
        "keyboard shortcut for emoji on mac",
        "what should i name my wifi",
        // planning / generation asks (mirror of listy notes)
        "plan a weekend trip to kyoto",
        "plan a birthday party for a 6 year old",
        "build me a study plan for ielts",
        "make me a workout for leg day",
        "give me ideas for date night",
        "what should i read after atomic habits",
        "whats worth watching on netflix right now",
        "what's a good podcast about startups",
        "remind me how reduce works in python",
        // number-flavored asks (digits shouldn't drag a question into note)
        "how many days until christmas",
        "what is 18% of 230",
        "square root of 7056",
        "how many ounces in a liter",
        "whats 230 euros in dollars",
        "how long is a marathon",
        // title / media asks (book and show names shouldn't read as a queue jot)
        "who directed inception",
        "who sings bohemian rhapsody",
        "who painted the starry night",
        "is the three body problem worth reading",
        "what is dune about",
        "summary of atomic habits",
        "is severance any good",
        "books like project hail mary",
        // noun-phrase information asks (no verb, still a lookup)
        "best stretches for lower back",
        "dinner ideas without meat",
        "gift ideas for mom",
        "weekend trip ideas near seattle",
        "side effects of melatonin",
        "difference between 401k and ira",
        "pros and cons of electric cars",
        "meaning of deja vu",
        "synonyms for happy",
        "capital of switzerland",
        "population of japan",
        "calories in a banana",
        // pure arithmetic (digit-heavy but still a question)
        "what's 48 plus 67",
        "1024 divided by 3",
        "98 times 76",
        "what is 2 to the 10th",
        "sqrt of 144",
        "cube root of 729",
        "factorial of 10",
        "what's 20% off 149",
        "average of 12 18 25",
        "30 dollars a day for a year is how much",
        // greetings / social / meta-dialogue aimed at the assistant, not a jot
        "hello",
        "hello there",
        "hi",
        "hi there",
        "hey",
        "hey there",
        "good morning",
        "good evening",
        "how are you",
        "how's it going",
        "thanks",
        "thank you",
        "thanks a lot",
        "who are you",
        "what are you",
        "what can you do",
        "what's your name",
        "tell me about yourself",
        "let's chat",
        "talk to me",
        "keep going",
        "continue",
        "try again",
        "another one",
        "more detail please",
        "make it simpler",
        "i didn't get that explain again",
        // App-setting commands are assistant tasks: route them to Ask so the
        // confirmed settings tool sees them, never into the note capture path.
        "set the app language to simplified chinese",
        "switch the interface language to english",
        "hide the app icon from the dock",
        "don't show the menu bar icon",
        "don't launch this app at login",
        "start this app automatically when i log in",
        "set hover sensitivity to low",
        "turn off hide in full screen",
        "save my notes to a markdown folder",
        "change the summon shortcut to command shift k",
        "show me all current app settings",
        "what keyboard shortcuts does this app have",
        "which hotkeys does notch support",
        "what is the shortcut to summon the app",
        // question-marked variants (the mark itself is a cue worth teaching;
        // the Chinese set carries a couple of these too)
        "hello?",
        "are you there?",
        "can dogs eat grapes?",
        "what time is it in tokyo?",
        "is this correct?",
        "how does this work?",
        "any ideas?",
    ]

    // MARK: - English · note

    private static let englishNote: [String] = [
        // todos
        "buy milk",
        "milk eggs bread detergent",
        "pick up dry cleaning",
        "call mom",
        "call the dentist tomorrow",
        "renew passport",
        "pay rent",
        "pay electricity bill",
        "email the landlord about the leak",
        "reply to hr about offer by friday",
        "detergent almost out",
        "cat food 3 days left",
        "top up laundry card",
        "bring badge",
        "wear formal tomorrow client visit",
        "ikea this weekend look at sofas",
        "black friday list vacuum air fryer",
        "groceries soy sauce vinegar garlic ginger",
        "replace badge at reception",
        "parents visiting next week clean guest room",
        "sleep in sunday",
        "rsvp by friday",
        // time-stamped
        "dentist tuesday 3pm",
        "rent due friday",
        "flight ua882 june 18 9:40am",
        "train to boston 7:05 track 9",
        "lunch with li wed 12:30",
        "dinner 7pm hotpot with kai",
        "parent teacher meeting thu 7pm",
        "piano moved to saturday 10am",
        "haircut sat 11am with tony",
        "interview candidate wed 2pm ios role",
        "booked room 1401 for 4pm",
        "monday standup moved to 9:30",
        "team dinner tonight eat light",
        "reunion aug 2 old campus",
        "lab results ready thursday",
        "second shot june 25",
        "braces checkup every 6 weeks",
        "car ready thursday says mechanic",
        "up at 6:30 to catch the train",
        "set alarm for 5:50",
        "shuttle leaves 6:10 north gate",
        "pickup point closes at 8pm",
        "cafeteria has grilled fish wednesday",
        "that shop closed mondays",
        "expense report due end of month",
        "deadline paper submission july 15",
        "server renews june 30",
        "car insurance renews july 8",
        "license renewal before december",
        "passport expires march 2027",
        "gym membership expires in march",
        "contacts due end of april",
        "mortgage autopay on the 19th",
        "preschool lunch fee 300",
        // info jots
        "wifi pw sunflower99",
        "guest wifi cafe_blue pass latte2026",
        "parked on b2-077",
        "parking spot 144 level 3",
        "locker code 0427",
        "gym locker 217",
        "gate code #2046",
        "hotel confirmation 8829137",
        "airbnb checkin 3pm code 4416",
        "airbnb address 12 rue cler",
        "key at front desk under my name",
        "itinerary osaka 3d kyoto 2d",
        "visa docs employment letter bank statement photos",
        "new coworker is priya on design",
        "landlord number 555 0132",
        "building mgmt 555 8821",
        "invoice number 2026-0613",
        "tax id 84-2210334",
        "salary hits the 6679 card",
        "hoa fee 280 paid",
        "insurance policy picc2026088123",
        "changed password to Glass#2026",
        "router admin 192.168.31.1",
        "test account demo01 pass 123456",
        "macbook serial c02zk1anlvdq",
        "ev charger slot 3 is broken",
        "use 95 octane",
        "tire pressure 2.3 front 2.5 rear",
        "next service at 62000 km",
        "gas meter 3327",
        "package shipped sf1352847569988",
        "return label 773310928",
        "renew domain notchglass.app",
        "metro card under $10",
        "glasses left 4.50 right 4.75",
        "shoe size 37 for sis",
        "leftovers in fridge for lunch",
        "water succulents weekly",
        "vitamin d daily after breakfast",
        "antibiotics until friday",
        "updated 401k contribution to 8%",
        "onboarding docs id diploma health report",
        // reminder phrasing
        "remember to water the plants",
        "remember sunscreen tomorrow",
        "don't forget the charger",
        "dont forget lunch with sam",
        "remind me to send the invoice monday",
        "todo update resume email recruiter",
        "todo write weekly report",
        // ideas
        "idea pomodoro timer in the notch",
        "idea for blog ai and attention",
        "app idea split bills with roommates",
        "gift idea for dad fishing rod",
        "mom's birthday may 12",
        "anniversary sept 3",
        "idea recent as a timeline",
        "research raycast ai entry ux",
        "competitors alfred spotlight raycast",
        "bug hint flickers with chinese ime",
        "fix settings scrollbar",
        "shipped v0.4.2",
        "wedding gift 800 for zhou",
        // records / logs
        "weight 71.5 kg",
        "ran 5k today 27:40",
        "bench 3x8 at 60kg",
        "blood pressure 122/79",
        "day 7 no sugar",
        "no bubble tea day 3",
        "lights out by 11",
        "talked to landlord answer by end of month",
        "boss said q3 budget cut 10%",
        "sent the mockups to jake",
        "meeting notes v1 design due tuesday",
        "weekly report shipped auto routing",
        "q3 okr retention +5%",
        "late night taxi is reimbursable",
        "trainer says start with back",
        "book note focus is scarce",
        "quote slow is smooth smooth is fast",
        "movies to watch dune 2 oppenheimer",
        "show rec severance s2",
        "add to playlist lemon kenshi yonezu",
        "reading list thinking fast and slow",
        "restaurant shortlist tsuta konjiki hototogisu",
        "coffee beans yirgacheffe medium roast good",
        "sofa kivik 4999",
        // remind-me phrasing (the note side of "remind me")
        "remind me to call the bank",
        "remind me about the dentist thursday",
        "remind me to take out the trash tonight",
        "remind me to renew the parking permit",
        // media / reading queues
        "books to read atomic habits deep work",
        "watchlist the bear season 3",
        "to watch shogun",
        "to read the three body problem",
        "podcast queue acquired huberman",
        // idea jots
        "idea dark mode for the widget",
        "idea weekly email digest",
        "feature idea quick capture hotkey",
        "startup idea ai meal planner",
        // status logs / done items
        "sent the invoice to acme",
        "sent the deck to legal",
        "pushed the fix to staging",
        "told the landlord about the leak",
        "finished chapter 4",
        "ordered the standing desk",
        "booked flights for august",
        "paid the water bill",
        "submitted the expense report",
        "emailed the professor about office hours",
        // people / facts someone told me
        "new pm is marcus from stripe",
        "sarah moved to the platform team",
        "doctor said cut back on caffeine",
        "mechanic recommends new brake pads soon",
        "dentist rec dr lee on 5th ave",
        // short plans
        "gym after work",
        "leg day tomorrow",
        "no meetings friday",
        "wfh wednesday",
        "early standup tomorrow",
        "date night saturday",
        "movie night sunday with the kids",
        // errands / trip prep lists
        "errands bank post office pharmacy",
        "weekend plans hike farmers market",
        "trip prep buy adapter download maps",
        // deictic captures (referent lives on the clipboard, not in the line)
        "save this link",
        "add this to my reading list",
        "bookmark this",
        "note this url",
        "save this snippet",
        "keep this",
        "file this away",
        "save this for later",
        "jot this down",
        "add this to my notes",
        "save this page",
        "note this down",
    ]
}
