import Foundation

/// English interface copy. `L` keeps call sites concise while every shipped
/// string now resolves from this one catalog.
@inline(__always)
func L(_ key: String) -> String {
    Strings.en[key] ?? key
}

func L(_ key: String, _ args: CVarArg...) -> String {
    String(format: L(key), arguments: args)
}

enum Strings {
    static let en: [String: String] = [
        // Settings shell
        "settings.title": "Settings",
        "navigation.backTo": "Back to %@",
        "settings.back": "Back to prompt",
        "sidebar.model": "Model",
        "sidebar.search": "Search",

        "sidebar.capture": "Capture",
        "sidebar.general": "General",
        "sidebar.appearance": "Appearance",
        "general.advanced": "Advanced",
        "sidebar.about": "About",
        "sidebar.stats": "Stats",
        "stats.conversations": "Chat msgs",
        "stats.captures": "Notes & reminders",
        "stats.agentRuns": "Agent msgs",
        "stats.tokens": "Tokens",
        "stats.tokens.info": "Counted from v0.6.0 on.",
        "stats.privacy": "Stats stay on this Mac.",
        "stats.privacy.info": "Counted from the history already on this Mac, and never sent anywhere. See the privacy policy for more.",
        "stats.privacy.info.link": "privacy policy",
        "stats.earlier": "Earlier",
        "stats.later": "Later",
        "stats.peakHour": "Peak hour",
        "stats.activeDays": "Active days",
        "stats.currentStreak": "Current streak",
        "stats.longestStreak": "Longest streak",
        "stats.dayTip": "%1$@ · %2$@",
        "stats.dayTip.chat": "%@ chat messages",
        "stats.dayTip.chat.one": "%@ chat message",
        "stats.dayTip.notes": "%@ notes",
        "stats.dayTip.notes.one": "%@ note",
        "stats.dayTip.agent": "%@ agent messages",
        "stats.dayTip.agent.one": "%@ agent message",
        "stats.empty": "No activity yet",
        "sidebar.shortcuts": "Shortcuts",
        "shortcuts.group.summon": "Summoning",
        "shortcuts.group.prompt": "Prompt",
        "shortcuts.group.answer": "Answer",
        "shortcuts.group.panel": "Panel",
        "shortcuts.summon": "Open Notch",
        "shortcuts.send": "Send the line",
        "shortcuts.sendOther": "Send as the other kind (Ask ⇄ Note)",
        "shortcuts.cycleIntent": "Cycle Ask / Note / Reminder",
        "shortcuts.bucket": "Switch Ask ⇄ Agent",
        "shortcuts.recall": "Recall past questions, walk Recent",
        "shortcuts.slash": "Commands",
        "shortcuts.pasteImage": "Attach a copied screenshot to an agent task",
        "shortcuts.copyAnswer": "Copy the answer",
        "shortcuts.regenerate": "Regenerate the answer",
        "shortcuts.pin": "Keep the panel open",
        "shortcuts.newChat": "Start a fresh conversation",
        "shortcuts.back": "Back to the prompt",
        "shortcuts.filter": "Filter Recent",
        "shortcuts.picker": "Model & agent picker",
        "shortcuts.detach": "Split into its own window",
        "shortcuts.or": "or",
        "shortcuts.reset": "Restore default",
        "shortcuts.promptAction": "Prompt shortcuts",
        "shortcuts.promptAction.add": "Add prompt shortcut",
        "shortcuts.promptAction.empty": "Bind a shortcut to a prompt and run it on selected text.",
        "shortcuts.promptAction.placeholder": "Prompt for the selected text",
        "shortcuts.promptAction.set": "Set",
        "shortcuts.promptAction.edit": "Edit",
        "shortcuts.promptAction.delete": "Delete prompt shortcut",
        "shortcuts.promptAction.done": "Done",
        "whatsnew.action.forceClick": "Set Force Click",
        "whatsnew.forceClick.caption": "Turn off Look up in System Settings → Trackpad",
        "shortcuts.promptAction.more": "More options",
        "shortcuts.promptAction.openIn": "Open in",
        "shortcuts.promptAction.openIn.notch.short": "The notch",
        "shortcuts.promptAction.openIn.window.short": "Beside the pointer",
        "shortcuts.promptAction.forceTouch": "Show in Force Click",
        "shortcuts.promptAction.model": "Model",
        "shortcuts.promptAction.model.default": "Default model",
        "shortcuts.promptAction.window.context": "Using copied text",
        "shortcuts.promptAction.window.context.drop": "Drop the copied text",
        "selection.context": "Using selected text",
        "selection.context.from": "Using selected text from %@",
        "selection.context.drop": "Drop the selected text",
        "shortcuts.promptAction.window.placeholder": "What should I do with it?",
        "shortcuts.promptAction.window.noSelection": "No text selected",
        "shortcuts.conflict.usedBy": "Already used by “%@”.",
        "shortcuts.reserved.settings": "Open Settings",
        "shortcuts.reserved.system": "macOS",

        // Model section
        "model.provider": "Provider",
        "model.provider.noSearchGroup": "No built-in web search",
        "model.provider.noSearchReason": "No native web search. Add a search key in Settings → Search to enable it.",
        "model.apiKey": "API key",
        "model.pasteKey": "Paste your API key",
        "search.backend": "Search backend",
        "search.backend.native": "Default",
        "search.backend.keenable": "Keenable",
        "search.backend.exa": "Exa",
        "search.backend.anysearch": "AnySearch",
        "model.keenableApiKey": "Keenable key",
        "model.keenablePasteKey": "Paste your Keenable API key",
        "model.keenableHint": "A search backend for every model. Get a key at ",
        "model.keenableHint.host": "keenable.ai",
        "model.exaApiKey": "Exa key",
        "model.exaPasteKey": "Paste your Exa API key",
        "model.exaHint": "A search backend with full-text grounding. Get a key at ",
        "model.exaHint.host": "exa.ai",
        "model.anysearchApiKey": "AnySearch key",
        "model.anysearchPasteKey": "Paste your AnySearch API key",
        "model.anysearchHint": "Works anonymously without a key. Add one for higher limits at ",
        "model.anysearchHint.host": "anysearch.com",
        "model.anysearchAnonymous": "Anonymous tier",
        "model.addKey": "Add key",
        "model.test": "Test",
        "model.cancel": "Cancel",
        "model.change": "Change",
        "model.save": "Save",
        "model.saved": "Saved",
        "model.account": "Account",
        "model.disconnect": "Disconnect",
        "model.connecting": "Connecting…",

        // Codex (ChatGPT) — keyless backend that reuses `codex login`.
        "codex.status.connected": "Signed in via ChatGPT",
        "codex.status.getCodex": "Get Codex",
        "codex.action.reauthorize": "Re-authorize",
        "codex.action.signIn": "Sign in",
        "codex.status.hint.ready": "Notch runs your local Codex CLI — answers are billed to your ChatGPT plan.",
        "codex.status.hint.login": "Codex is installed. Run `codex login` in Terminal to sign in, then reopen this.",
        "codex.status.hint.install": "Install the Codex CLI and run `codex login`, then reopen Settings.",
        "codex.error.notInstalled": "Codex CLI not found. Install it and run `codex login`.",
        "codex.error.notSignedIn": "Not signed in to Codex. Run `codex login` in Terminal.",
        "codex.error.noOutput": "Codex returned no answer. Please try again.",
        "codex.error.spawnFailed": "Couldn't start the Codex CLI.",
        "codex.error.runFailed": "Codex failed:",
        "hint.agent": "Agent",
        "agent.folder.choose": "Choose folder…",
        // The Ask chip with nothing set up yet — same shape as the folder chip
        // above: name the gap, and be the way to close it.
        "model.choose": "Choose model…",
        "agent.pick.message": "Choose the folder to work in",
        "agent.placeholder": "Describe task…",
        "agent.imageAttached": "Attached image",
        "agent.imagesAttached": "%lld attached images",
        "agent.image.remove": "Remove image",
        "agent.folder.switch": "Change folder",
        "agent.disarm": "Exit agent mode",
        "agent.picker.model": "Model",
        "agent.effort": "Effort",
        "agent.effort.default": "Default",
        "agent.effort.low": "Low",
        "agent.effort.medium": "Medium",
        "agent.effort.high": "High",
        "agent.effort.xhigh": "X-High",
        "agent.effort.max": "Max",
        "agent.effort.ultra": "Ultra",
        "agent.running": "%@ is working in “%@”",
        "agent.runningCompact": "1 %@ agent",
        "agent.running.count": "%lld running",
        "agent.badgeCount": "%lld agent tasks",
        "agent.thinking": "Thinking…",
        "agent.trail.thinking": "Thinking",
        "agent.trail.plan": "Plan · %1$lld/%2$lld",
        "agent.trail.more": "Show all",
        "agent.trail.less": "Show less",
        "agent.trail.toBottom": "Jump to newest",
        "agent.followUp.interrupt": "⌘⏎ interrupt",
        "agent.followUp.send": "⏎ send",
        "agent.followUp.interrupt.help": "Stop this round and send now",
        "agent.trail.cmd.one": "1 command",
        "agent.trail.cmd.many": "%lld commands",
        "agent.trail.edit.one": "1 file edit",
        "agent.trail.edit.many": "%lld file edits",
        "agent.trail.read.one": "1 read",
        "agent.trail.read.many": "%lld reads",
        "agent.trail.search.one": "1 search",
        "agent.trail.search.many": "%lld searches",
        "agent.trail.tool.one": "1 tool call",
        "agent.trail.tool.many": "%lld tool calls",
        "agent.done": "%@ finished in %@",
        "agent.failed": "%@ task failed",
        "agent.cancelled": "Task cancelled",
        "agent.interrupted": "Task interrupted — Notch quit while it was running",
        "agent.interrupted.resume": "Pick the session back up: %@",
        "agent.resume": "Resume in %@",
        "agent.cancel": "Cancel task",
        "agent.cancelConfirm": "Cancel task?",
        "agent.openFolder": "Open folder",
        "agent.openResult": "View the result",
        "agent.dismiss": "Dismiss",
        "agent.filesChanged": "%lld files changed",
        "agent.detail": "Details",
        "agent.detail.empty": "No activity yet",
        "agent.detail.model": "Model · %@",
        "agent.detail.context": "Context · %@",
        "agent.followUp.placeholder": "Ask a follow-up…",
        "agent.followUp.queue": "Queue a follow-up…",
        "notify.agent.done": "%@ task succeeded",
        "notify.agent.failed": "%@ task failed",

        // Claude Code — keyless backend that reuses the user's own `claude` sign-in.
        // Deliberately no in-app sign-in copy: the user signs in in Terminal.
        "claudecode.status.connected": "Signed in via Claude",
        "claudecode.status.signedOut": "Not signed in",
        "claudecode.status.get": "Get Claude Code",
        "claudecode.status.hint.ready": "Notch runs your local Claude Code CLI — answers are billed to your Claude plan.",
        "claudecode.status.hint.login": "Claude Code is installed. Run `claude` in Terminal and sign in, then reopen this.",
        "claudecode.status.hint.install": "Install Claude Code and run `claude` to sign in, then reopen Settings.",
        "claudecode.error.notInstalled": "Claude Code not found. Install it and run `claude` in Terminal to sign in.",
        "claudecode.error.notSignedIn": "Not signed in to Claude Code. Run `claude` in Terminal and sign in.",
        "claudecode.error.authExpired": "Claude Code sign-in expired. Open Terminal, run `claude`, then `/login` to sign in again.",
        "claudecode.error.noOutput": "Claude returned no answer. Please try again.",
        "claudecode.error.spawnFailed": "Couldn't start the Claude Code CLI.",
        "claudecode.error.runFailed": "Claude failed:",
        "grok.status.connected": "Signed in via xAI",
        "grok.status.get": "Get Grok CLI",
        "grok.action.reauthorize": "Re-authorize",
        "grok.action.signIn": "Sign in",
        "grok.status.hint.ready": "Notch runs your local Grok CLI — answers are billed to your xAI plan.",
        "grok.status.hint.login": "Grok CLI is installed. Sign in with `grok login` (or set XAI_API_KEY), then reopen this.",
        "grok.status.hint.install": "Install the Grok CLI and run `grok login`, then reopen Settings.",
        "grok.error.notInstalled": "Grok CLI not found. Install it and run `grok login`.",
        "grok.error.notSignedIn": "Not signed in to Grok. Run `grok login`, or set XAI_API_KEY.",
        "grok.error.authExpired": "Grok sign-in expired. Run `grok login` to sign in again.",
        "grok.error.sessionFailed": "Grok couldn't start a session — the Grok CLI likely needs updating. Run `grok update` in Terminal, then try again.",
        "grok.error.noOutput": "Grok returned no answer. Please try again.",
        "grok.error.spawnFailed": "Couldn't start the Grok CLI.",
        "grok.error.runFailed": "Grok failed:",

        "commandcode.status.connected": "Signed in to Command Code",
        "commandcode.status.signedOut": "Not signed in",
        "commandcode.status.get": "Get Command Code",
        "commandcode.status.hint.ready": "Notch runs your local Command Code CLI — answers are billed to your Command Code plan.",
        "commandcode.status.hint.login": "Command Code is installed. Run `cmd login` in Terminal (or set COMMAND_CODE_API_KEY), then reopen this.",
        "commandcode.status.hint.install": "Install Command Code (`npm i -g command-code`) and run `cmd login`, then reopen Settings.",
        "commandcode.error.notInstalled": "Command Code CLI not found. Install it and run `cmd login`.",
        "commandcode.error.notSignedIn": "Not signed in to Command Code. Run `cmd login`, or set COMMAND_CODE_API_KEY.",
        "commandcode.error.authExpired": "Command Code sign-in expired. Run `cmd login` to sign in again.",
        "commandcode.error.rateLimited": "Command Code rate limit reached. Try again in a moment.",
        "commandcode.error.outOfCredits": "Command Code is out of credits. Top up your account, then try again.",
        "commandcode.error.noOutput": "Command Code returned no answer. Please try again.",
        "commandcode.error.spawnFailed": "Couldn't start the Command Code CLI.",
        "commandcode.error.runFailed": "Command Code failed:",
        "pi.status.connected": "Signed in via PI",
        "pi.status.signedOut": "No provider signed in",
        "pi.status.get": "Get PI",
        "pi.status.hint.ready": "Notch runs your local PI CLI — each model is billed to whichever provider account you signed PI into.",
        "pi.status.hint.login": "PI is installed but no provider is signed in. Run `pi` in Terminal and use `/login`, or set a provider API key, then reopen this.",
        "pi.status.hint.install": "Install PI (`npm i -g @earendil-works/pi-coding-agent`) and sign in with `/login`, then reopen Settings.",
        "pi.error.notInstalled": "PI CLI not found. Install it and sign in with `/login`.",
        "pi.error.notSignedIn": "No provider is signed in to PI. Run `pi` and use `/login`, or set a provider API key.",
        "pi.error.authExpired": "PI sign-in expired. Run `pi` and use `/login` to sign in again.",
        "pi.error.rateLimited": "The provider behind this PI model hit a rate limit. Try again in a moment.",
        "pi.error.outOfCredits": "The provider behind this PI model is out of credit. Top up that account, then try again.",
        "pi.error.noOutput": "PI returned no answer. Please try again.",
        "pi.error.spawnFailed": "Couldn't start the PI CLI.",
        "pi.error.runFailed": "PI failed:",
        "busy.thinking": "Thinking",
        "busy.working": "Working",
        "busy.running": "Running",
        "busy.editing": "Editing",
        "busy.searching": "Searching",
        "busy.writing": "Writing",
        "model.finishSignIn": "Finish signing in in your browser…",
        "model.pasteInstead": "Paste a key instead",
        "model.connectOpenRouter": "Connect OpenRouter",
        "model.label": "Model",
        "model.refresh": "Refresh model lists",
        "model.picker.switch": "Switch model",
        "model.default": "Default (%@)",
        "model.freeFeatured": "Best free models",
        "model.freeMore": "More free models",
        "model.picker.configured": "Configured",
        "model.picker.unconfigured": "No key yet",
        "model.picker.default": "Default",
        "model.picker.empty": "No matching models",
        "model.picker.addKey": "Add key",
        "model.picker.more": "More models…",
        "model.picker.moreModels": "More models",
        "model.keys.section": "API key",
        "model.setup.needed": "Set up %@ to start asking.",
        "model.pending.hint": "Add a key for %@ to use %@.",
        "model.footer.openrouter.pre": "Free to use — Connect signs you in to ",
        "model.footer.openrouter.host": "openrouter.ai",
        "model.footer.openrouter.post": " and stores a key on this Mac. Free models have a daily cap; add credits there to raise it.",
        "model.footer.byok.pre": "Stored on this Mac. Get a key at ",
        "model.footer.byok.post": ".",
        "model.footer.env": "A key from the %@ environment variable is in use; it overrides these fields.",
        "model.custom.defaultName": "Custom endpoint",
        "model.custom.name": "Name",
        "model.custom.url": "Base URL",
        "model.custom.urlPlaceholder": "http://localhost:11434",
        "model.custom.model": "Model ID",
        "model.custom.modelPlaceholder": "The id your server serves, e.g. llama3.2",
        "model.custom.resolved": "Requests go to %@",
        "model.custom.footer": "Any OpenAI-compatible endpoint — a local server (Ollama, LM Studio, vLLM), a gateway, or a vendor not listed here. The API key is optional: leave it empty for a server that needs none.",

        // Connectivity verdicts
        "conn.ok": "Key verified",
        "conn.missingKey": "Enter a key",
        "conn.unauthorized": "Invalid key",
        "conn.serverError": "Server error (%lld)",
        "conn.offline": "No connection",
        "conn.timedOut": "Timed out",
        "conn.unavailable": "Test unavailable for this provider",
        "conn.unexpected": "Unexpected response",

        // General section
        "general.showOn": "Show on",
        "general.appPresence": "App presence",
        "general.placement.footer": "External monitors get a menu-bar-height island.",
        "general.dockIcon": "Dock icon",
        "general.dockIcon.toggle": "Show in Dock",
        "general.dockIcon.footer": "Hidden keeps it a pure overlay — summon with ⌘, or by hovering the notch.",
        "general.menuBarIcon": "Menu bar icon",
        "general.menuBarIcon.toggle": "Show in menu bar",
        "general.menuBarIcon.hint": "Open Notch, start a chat, or switch models from the menu bar.",
        "menuBar.open": "Open Notch",
        "menuBar.newChat": "New Chat",
        "menuBar.history": "History…",
        "menuBar.model": "Model",
        "menuBar.modelSettings": "Model Settings…",
        "menuBar.noModel": "No model set up",
        "menuBar.settings": "Settings…",
        "menuBar.about": "About",
        "menuBar.version": "Version %@",
        "menuBar.whatsNew": "What's New",
        "menuBar.checkUpdates": "Check for Updates…",
        "menuBar.update": "Update to %@…",
        "menuBar.quit": "Quit Notch",
        "general.launchAtLogin": "Launch at login",
        "permissions.title": "System permissions",
        "permissions.reminders": "Reminders",
        "permissions.notes": "Notes automation",
        "permissions.notifications": "Notifications",
        "permissions.accessibility": "Accessibility",
        "permissions.location": "Location",
        "utilities.keepAwake": "Awake",
        "utilities.output": "Output",
        "utilities.shortcut": "Shortcut",
        "utilities.join": "Join %@",
        "utilities.power.title": "Power",
        "utilities.power.awakeOff": "Off",
        "utilities.power.now": "Right now",
        "utilities.power.sleepDisplay": "Sleep display",
        "utilities.power.screensaver": "Start screensaver",
        "utilities.power.close": "Close",
        "utilities.devices.batteries": "Batteries",
        "utilities.devices.none": "No devices found",
        "utilities.devices.charging": "Charging",
        "utilities.shortcuts.none": "No Shortcuts found",
        "utilities.shortcuts.create": "Create a Shortcut",
        "permissions.status.checking": "Checking…",
        "permissions.status.notGranted": "Not granted",
        "permissions.status.denied": "Denied",
        "permissions.status.granted": "Granted",
        "permissions.status.unavailable": "Unavailable",
        "permissions.action.allow": "Grant Access",
        "permissions.action.settings": "Open Settings",
        "appearance.handwritten": "Handwritten answers",
        "appearance.handwritten.hint": "Prose only \u{2014} code blocks and copied text are unchanged.",
        "appearance.style": "Style",
        "appearance.behavior": "Behavior",
        "appearance.displays": "Displays",
        "appearance.appIcon": "App icon",
        "appIcon.original": "Original",
        "appIcon.dot": "Dot",
        "appearance.liveActivity": "Live activity",
        "appearance.liveActivity.hint": "Show previews on the collapsed notch. Turn it off to keep the notch clear.",
        "network.proxy": "Proxy",
        "network.proxy.hint": "Used for AI requests and the Claude / Codex CLIs. Leave empty to follow the system proxy.",
        "network.proxy.placeholder": "http://127.0.0.1:7890",
        "network.proxy.status.manual": "App and agents connect through %@",
        "network.proxy.status.inherited": "Auto: agents inherit %@ from the environment",
        "network.proxy.status.system": "Auto: system proxy — %@",
        "network.proxy.status.shell": "Auto: agents use the login shell proxy — %@",
        "network.proxy.status.none": "Auto: no proxy found, connecting directly",
        "general.noteDestination": "Save notes to",
        "general.noteFolder.choose": "Choose…",
        "noteDest.appleNotes": "Apple Notes",
        "noteDest.folder": "Folder",
        "general.customInstructions": "Custom instructions",
        "general.customInstructions.placeholder": "e.g. Always answer in English",
        "general.customInstructions.hint": "A short preference added to every Ask — like \"prefer code\" or \"use metric\".",
        "general.copySense": "Copy sensing",
        "general.copySense.hint": "Copy a note or reminder, press ⌘C again to file it.",
        "sense.note": "To Save",
        "sense.reminder": "To Save",
        "sense.saved": "Saved",
        // Focus-timer phase boundary, on the resting notch's shoulders
        "focus.ear.focusOver": "Focus over", "focus.ear.breakStarted": "Break started",

        // Resting-notch notification ears
        "alert.notifications.a11y": "%lld new from %@",
        "focus.ear.breakOver": "Break over", "focus.ear.streakMarked": "Streak marked",
        "sense.failed": "Couldn't save",
        "general.shortcut": "Shortcut",
        "general.shortcut.resetTo": "Reset To",
        "general.shortcut.recording": "Type a shortcut…",
        "general.shortcut.off": "Off",
        "general.shortcut.reset": "Reset to double-tap ⌥",
        "general.shortcut.disable": "Turn off",
        "general.shortcut.needModifier": "Add ⌘, ⌥ or ⌃ — a bare key fires too easily.",
        "general.shortcut.reserved": "⌘, already opens Settings. Pick another.",
        "general.forceClickPressure": "Force click pressure",
        "general.forceClickPressure.hint": "How firmly you press selected text to open NotchFlow.",
        "general.selectionContext": "Use selected text",
        "general.selectionContext.hint": "Bring selected text into NotchFlow when it opens.",
        "selection.context.hint.off": "You can turn this off in Settings",
        "forceClick.off": "Off",
        "forceClick.light": "Light",
        "forceClick.medium": "Medium",
        "forceClick.firm": "Firm",
        "forceClick.lookup.title": "Turn off macOS Look up",
        "forceClick.lookup.body": "The same press also opens macOS Look up. Turn off “Look up & data detectors” in System Settings → Trackpad.",
        "forceClick.lookup.open": "Open Settings",
        "general.hoverSensitivity": "Hover sensitivity",
        "general.hoverSensitivity.hint": "How long the pointer must rest on the notch before it opens. Low waits 0.5 seconds, Balanced waits 0.25 seconds, and Instant opens immediately. Click peeks on hover; a click opens the panel.",
        "hover.click": "Click",
        "hover.low": "Low",
        "hover.balanced": "Balanced",
        "hover.instant": "Instant",
        "placement.all": "All displays",
        "placement.builtIn": "Built-in display",
        "dock.hidden": "Hidden",
        "dock.shown": "Shown",

        // About section
        "about.update.to": "Update to %@",
        "about.updating": "Updating…",
        "about.updateFailed": "Update failed — get it from the releases page",
        "about.github": "GitHub",
        "about.starGithub": "Star",
        "about.followX": "Follow",
        "about.buyCoffee": "Buy Me a Coffee",
        "about.privacy": "Privacy",
        "about.feedback": "Feedback",
        "about.whatsNew": "What's New",
        "about.group.updates": "Updates",
        "about.group.more": "More",
        "about.group.help": "Help",
        "about.checkForUpdates": "Check for updates",
        "about.checking": "Checking…",
        "about.upToDate": "You're up to date",
        // CC BY 4.0 requires the credit, the link, and a note that it was changed.
        "about.music": "Intro music: excerpt from R. Strauss, “Also sprach Zarathustra,” performed by Philip Milman via classicals.de. Edited for the intro. Licensed under CC BY 4.0.",
        "about.handwritingFont": "Handwriting: Caveat by Pablo Impallari, released under the SIL Open Font License 1.1.",
        "about.thinkingOrbs": "Loading animation: thinking-orbs (https://github.com/Jakubantalik/thinking-orbs), a dotted thought-orb loading indicator for AI & agent UIs, by Jakub Antalik, released under the MIT License.",
        "about.interactionKit": "Image gallery: the expanding image stack and the image modal are ports of Interaction Kit (https://interactionkit.org), a collection of copy-ready interaction components by Armond Schneider, released under the MIT License.",
        "gallery.expand": "Expand image stack",
        "gallery.collapse": "Collapse image stack",
        "gallery.previous": "Previous image",
        "gallery.next": "Next image",
        "about.replayIntro": "Replay intro",
        "about.licenses": "License",

        // Trial and perpetual Lemon Squeezy license
        "license.title": "Unlock NotchFlow",
        "license.checking": "Checking your license…",
        "license.trial": "Free trial",
        "license.trial.remaining": "%lld days left in your free trial",
        "license.trial.remaining.one": "1 day left in your free trial",
        "license.blocked.title": "Your 7-day trial has ended",
        "license.blocked.body": "Buy NotchFlow to keep using the app, or activate the lifetime license you already purchased.",
        "license.settings.locked": "Unlock full settings after purchase.",
        "license.invalid.body": "This license is no longer valid. Activate another key to use NotchFlow.",
        "license.configuration.body": "Purchases are not configured in this build. Contact NotchFlow support.",
        "license.storage.body": "NotchFlow cannot access secure license storage. Restart the app or contact support.",
        "license.licensed": "Lifetime license active",
        "license.licensed.body": "This Mac can use NotchFlow and all future updates forever.",
        "license.buy": "Buy NotchFlow",
        "license.activate": "Activate license",
        "license.activating": "Activating…",
        "license.deactivate": "Deactivate it for this Mac",
        "license.deactivating": "Deactivating…",
        "license.key": "License key",
        "license.key.placeholder": "Paste your Lemon Squeezy license key",
        "license.email": "Purchase email",
        "license.email.placeholder": "you@example.com",

        // What's New
        "whatsnew.title": "What's New",
        "whatsnew.back": "Back to prompt",
        "whatsnew.currentBadge": "CURRENT",
        "whatsnew.cue": "What's New",
        "whatsnew.section.features": "FEATURES",
        "whatsnew.section.improvements": "IMPROVEMENTS",
        "whatsnew.section.fixes": "FIXES",
        "whatsnew.section.others": "OTHERS",
        "whatsnew.empty": "Release notes aren't available right now.",
        "whatsnew.viewReleases": "View on Releases",
        "whatsnew.viewAllReleaseNotes": "View all release notes",

        // Idle / input
        "input.placeholder": "Type anything…",
        "input.saving": "Saving…",
        "input.copiedPrefix": "Copied: %@",
        "hint.ask": "Ask",
        "hint.note": "Note",
        "hint.remind": "Remind",
        "hint.capture": "Capture",
        // The prompt's placeholder while `/` (or Tab) has pinned a destination —
        // an empty field has no glyphs for the inline ghost to trail, so the
        // placeholder is what says where the next line is going.
        "note.placeholder": "Write a note…",
        "remind.placeholder": "Remind me to…",
        // Sits after the lone "/" while the command menu is up.
        "slash.filter": "Type to filter",

        "recur.daily": " · Daily",
        "recur.weekly": " · Weekly",
        "recur.weeklyOn": " · Weekly · %@",
        "recur.monthly": " · Monthly",

        // Recent list
        "recent.manage": "More",
        "recent.collapse": "Back",
        "recent.settings": "Settings (⌘,)",
        "recent.menu.settings": "Settings",
        "recent.menu.checkForUpdates": "Check for updates",
        "recent.menu.releaseNotes": "Release notes",
        "recent.menu.seeAll": "See all history",
        "recent.menu.shortcuts": "Keyboard shortcuts",
        "recent.menu.stats": "Stats",
        "history.window.title": "History",
        "history.window.search": "Search history",
        "history.window.filter.all": "All",
        "history.window.filter.ask": "Ask",
        "history.window.filter.notes": "Notes",
        "history.window.filter.reminders": "Reminders",
        "history.window.filter.agent": "Agent",
        "detached.open": "Split into its own window (⌃⇧=)",
        "detached.thread.title": "Conversation",
        "detached.thread.subtitle": "Conversation",
        "detached.continueInNotch": "Back to notch",
        "detached.continueInNotch.help": "Hand this session back to the notch",
        "detached.task.gone": "This run is no longer available.",
        "detached.task.cancel": "Stop this run",
        "detached.close": "Close window",
        "history.window.count": "%lld items",
        "history.window.empty": "No history yet",
        "history.window.empty.agent": "No agent conversations yet",
        "history.window.empty.filtered": "Nothing matches",
        "history.window.detail.empty": "Select a conversation",
        "history.detail.you": "You",
        "history.detail.assistant": "Assistant",
        "recent.clear": "Clear",
        "recent.clear.agent": "Clear agent history",
        "recent.filter": "Filter…",
        "recent.filter.note": "Note",
        "recent.filter.remind": "Remind",
        "recent.filter.ask": "Ask",
        "recent.filter.agent": "Agent",
        "recent.filter.clear": "Clear filter",
        "recent.badge.notes": "Notes",
        "recent.badge.reminders": "Reminders",
        "recent.hint.note": "Opens this note in Notes",
        "recent.hint.reminder": "Opens this reminder in Reminders",
        "recent.hint.ask": "Reopens this conversation",
        "recent.answering": "Answering…",
        "recent.delete": "Delete",
        "recent.recent": "Recent",

        // Clear-history confirm
        "clear.title": "Clear recent history?",
        "clear.body": "This permanently removes all recent questions. This can't be undone.",
        "clear.body.scope": "Choose how far back to clear. This can't be undone.",
        "clear.scope.lastDay": "Last 24 Hours",
        "clear.scope.all": "Everything",
        "clear.cancel": "Cancel",
        "clear.confirm": "Clear History",
        "clear.agent.title": "Clear agent history?",
        "clear.agent.body": "This permanently removes every agent conversation. Other history stays.",
        "clear.agent.confirm": "Clear agent history",

        // Result / thread
        "result.setUpModel": "Set up your model",
        "result.basedOnCopied": "Based on what you copied",
        "result.you": "You",
        "result.newConversation": "New conversation (←)",
        "result.pin": "Pin (⌘P)",
        "result.unpin": "Unpin (⌘P)",
        "result.copiedToClipboard": "Copied to clipboard",
        "result.copyAnswer": "Copy answer (⌘C)",
        "result.copyMarkdown": "Copy as Markdown (⌘C)",
        "result.replaceOriginal": "Replace original text",
        "result.copyPlainText": "Copy as plain text",
        "result.completedAt": "Completed %@",
        "result.regenerate": "Regenerate (⌘R)",
        "result.regenerate.menu": "Regenerate (⌘R)",
        "result.regenerate.with": "Regenerate with…",
        "result.regenerate.current": "%@ (current)",
        "result.copyToContinue": "Copy chat to continue in ChatGPT or Claude",
        "result.model": "Model",
        "result.modelUsed": "Answered by %@",
        "result.followUp": "Ask a follow-up…",
        "result.followUp.agent": "Ask the chat model about this run…",
        "result.followUp.agentContinue": "Follow up with %@…",
        "result.followUp.agentQueue": "%@ is working — queue a follow-up…",
        "history.detail.agent.failed": "Failed",
        "history.image.open": "Open image",
        "bubble.showMore": "Show more",
        "bubble.showLess": "Show less",
        "ask.visionHint": "The selected model may not support images — try a vision-capable model.",

        // Feedback / errors
        "feedback.addedNotesClip": "Added to Notes · with clipboard",
        "feedback.addedNotes": "Added to Notes",
        "feedback.notesFailed": "Couldn't save to Notes. Try again.",
        "feedback.addedFile": "Added to notes folder",
        "feedback.addedFileClip": "Added to notes folder · with clipboard",
        "feedback.fileFailed": "Couldn't write the note file. Try again.",
        "feedback.addedReminders": "Added to Reminders%@",
        "feedback.remindersFailed": "Couldn't save to Reminders. Try again.",
        "feedback.savePreservedLine": "%1$@\n%2$@",
        "error.generic": "Something went wrong. Try again.",
        "error.retry": "Try again",
        "error.openSettings": "Open Settings",
        "error.interrupted": "\n\n— connection lost; answer may be incomplete.",
        "error.truncated": "\n\n— answer cut off (hit the length limit).",
        "error.noAnswer": "No answer came back.",
        "recent.badge.failed": "Failed",
        "notify.answerReady.title": "Answer ready",

        // Relative time
        "time.justNow": "just now",
        "time.minutesAgo": "%lldm ago",
        "time.hoursAgo": "%lldh ago",
        "time.daysAgo": "%lldd ago",

        // Service errors
        "notes.error.permission": "Allow access to Notes in System Settings → Privacy & Security → Automation.",
        "notes.error.unavailable": "Couldn't reach Notes. Try again.",
        "notes.file.error.folder": "Couldn't create the notes folder. Check its location in Settings.",
        "notes.error.fallback": "Couldn't save to Notes.",
        "reminders.error.permission": "Allow access in System Settings → Privacy & Security → Reminders.",
        "reminders.error.noList": "No Reminders list found. Open the Reminders app once, then try again.",

        // AI service errors / stub
        "service.error.http": "%@ request failed (HTTP %lld).",
        "service.error.malformed": "%@ returned an unexpected response.",
        "stub.noModel": "No model connected yet — this is the offline stub. Open Settings (⌘,) and connect a free OpenRouter account (or paste an API key) to get live answers.",

        // OpenRouter OAuth
        "or.error.noPort": "Couldn't open a local port for the sign-in redirect",
        "or.error.cancelled": "Sign-in was cancelled in the browser",
        "or.error.noKey": "OpenRouter didn't issue a key — try connecting again",
        "or.error.unreachable": "Couldn't reach OpenRouter — check your connection and try again",

        // OpenRouter browser-redirect pages (shown in the user's browser)
        "or.page.connected.title": "Connected",
        "or.page.connected.line": "NotchFlow is connected — you can close this tab.",
        "or.page.cancelled.title": "Cancelled",
        "or.page.cancelled.line": "Sign-in was cancelled. You can close this tab and try again from NotchFlow.",

        // Agent tool activity (shown on the streaming turn while a tool runs)
        "agent.activity.search": "Searching the web…",
        "agent.activity.refining": "Digging deeper…",
        "agent.activity.searchQuery": "Searching “%@”",
        "agent.activity.refiningQuery": "Digging into “%@”",
        "agent.activity.composing": "Reading the results…",
        // While reading results, the line names the page (its host) being read.
        "agent.activity.readingPage": "Reading %@",
        "agent.activity.clipboard": "Reading the clipboard…",
        "agent.activity.open": "Opening in your browser…",
        "agent.activity.time": "Checking the time…",
        "agent.activity.calc": "Calculating…",
        "agent.activity.history": "Looking through your history…",
        "agent.activity.askUser": "Waiting for your choice…",
        "agent.activity.working": "Working…",
        "agent.activity.runningTool": "Running %@…",
        "agent.activity.thinking": "Thinking…",

        // Source badge (under a search-grounded answer)
        "source.badge.help": "Sources",
        "source.badge.fallback": "Sources",
    ]


}
